config/routes.rb
Rails.application.routes.draw do
    get 'signup', to: 'users#new', as: 'signup'
    get 'login', to: 'sessions#new', as: 'login'
    post 'login', to: 'sessions#create', as: 'createlogin'
    get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :resources
  resources :users

# root 'users#index'
root 'home#index'
# resources :employers

get 'employers/' => 'employers#index', as: :employers

get 'employers/new' => 'employers#new', as: :new
 
post 'employers/' => 'employers#create'

get 'employers/:id' => 'employers#show', as: :employer

get 'employers/:id/edit' => 'employers#edit', as: :edit

patch 'employers/:id' => 'employers#update'

delete 'employers/:id' => 'employers#destroy'


# resources :users, only: [:index, :new, :create]
# resource :sessions, only: [:new, :create, :destroy]

end

# get 'beans/' => 'beans#index', as: :beans

# get 'beans/new' => 'beans#new'
 
# post 'beans/' => 'beans#create'

# get 'beans/:id' => 'beans#show', as: :bean

# get 'beans/:id/edit' => 'beans#edit', as: :edit_bean

# patch 'beans/:id' => 'beans#update'

# delete 'beans/:id' => 'beans#destroy'

app/models/employer.rb
class Employer
  include Mongoid::Document
  field :pay_period, type: Date
  field :income, type: Float
  field :health_insurance, type: Mongoid::Boolean
  field :benefits, type: Mongoid::Boolean
end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword

  # has_many :employers

  field :email, type: String
  field :password_digest, type: String
  field :investment_strategy, type: String
  field :health_insurance, type: String
  
  has_secure_password

  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_filter :authorize
protect_from_forgery wth: :exception

 private

  def current_user
  	
  	puts session[:user_id]
    @current_user ||= User.find(session[:user_id]["$oid"]) if session[:user_id] 
  end
  helper_method :current_user

end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
skip_before_filter :authorize
  def index
    @employers = Employer.all
  end

  def new
    @employer = Employer.new
  end

  def create
        @employer = Employer.new(params.require(:employer).permit(:pay_period, :income, :health_insurance, :benefits))
        if @employer.save
            redirect_to employers_path
        else
            render 'new'
        end
  end

  def show
    @employer = Employer.find(params[:id])
  end

  def edit
    @employer = Employer.find(params[:id])
  end

  def destroy
        @employer = Employer.find(params[:id])
        @employer.destroy
        redirect_to employers_path
  end

 
  def update
        @employer = Employer.find(params[:id])
        if @employer.update_attributes(params.require(:employer).permit(:pay_period, :income, :health_insurance, :benefits))
            redirect_to employers_path
        else
            render 'edit'
        end
  end

  

 

end

# field :pay_period, type: Date
#   field :income, type: Decimal
#   field :health_insurance, type: Mongoid::Boolean
#   field :benefits, type: Mongoid::Boolean

app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_before_filter :authorize
	def index
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize
  def new
  end
    def create
        user = User.where(email: params[:email]).first
        # first make sure we actually find a user
        # then see if user authenticates
        if user && user.authenticate(params[:password])
            # sets the cookie to the browser
            session[:user_id] = user.id
            redirect_to root_url, notice: "Logged in!"
        else
            flash.now.alert = "Email or password is invalid"
            render "new"
            # redirect_to new_session_path
        end
    end

    def destroy
        # Kill our cookies!
        reset_session
        redirect_to root_path, notice: "Logged out!"
    end

			 


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_filter :authorize
	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_url, notice: "Thank you for signing up"
		else
			render "new"
		end
	end

	private 
	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation, :investment_strategy, :health_insurance)
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beans_helper.rb
module BeansHelper
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/employers/edit.html.erb
   <h1> Edit an entry </h1>

    <%= form_for @employer do |f| %>
        Income: <%= f.text_field :income %>
        Pay Period: <%= f.text_field :pay_period %>
        Health Insurance: <%= f.text_field :health_insurance %>
        Benefits: <%= f.text_field :benefits %>

        <%= f.submit "Edit this entry!" %>

    <% end %>

    <%= link_to "Back to the list!", employers_path %>

 	
		
			
    

app/views/employers/index.html.erb
<div class="container">
	<div class="row">
		<div id="top">
		  <div class="col-md-12">
		  	<h1 class="user">Welcome USERNAME!</h1>
		  		<div class="link">
		  		<%= link_to "Add New Paystub", new_path %> 
		  		</div>
		  </div>
		</div>
	</div>

	<div class="row"> 
		<div id="content">
		  <div class="col-md-12">
			<h1 class="user2">Benefit's History</h1>
			<ul>
			<% @employers.each do |e| %>
			<li> 
			 Income	<%= e.income  %> 
			 Pay Period	<%= e.pay_period %> 
			 Health Insurance? <%= e.health_insurance %> 
			 Benefits?  <%= e.benefits %> 
			</li
			<%= link_to "More details!", employer_path(e) %> 
	    	 <% end %>
			</ul>
		  </div>
		</div>
	</div>
</div>

app/views/employers/new.html.erb
<h1> Add a Paystub!</h1>

    <%= form_for @employer do |f| %>
        Income: <%= f.text_field :income %>
        Pay Period: <%= f.text_field :pay_period %>
        Health Insurance: <%= f.text_field :health_insurance %>
        Benefits: <%= f.text_field :benefits %>

        <%= f.submit "Add Paystub!" %>

    <% end %>

    <%= link_to "Back to the list!", employers_path %>

      

app/views/employers/show.html.erb
<h1> USER NAME </h1>

<p> Below is the payment information for <%= @employer.pay_period %>

    Income: <%= @employer.pay_period %>
    Selected Health Insurance:  <%= @employer.health_insurance %>
    Selected Benefits: <%= @employer.benefits %>
	  



    <%= link_to "Edit this entry!", edit_path(@employer) %>
    <%= link_to "Delete this entry!", @employer, method: :delete, data: { confirm: 'Are you sure you want to delete it?' } %>
    <%= link_to "Back to the list!", employers_path %>

app/views/home/index.html.erb
<div class="header">
  
  <h2>Bringing 3rd Party Benefits to the On-Demand Employee</h2>
  <h5>VHR, inc.</h5>
<div>

<br>
<br>
<br>
<br>
<br>


<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>
 
  <!-- Wrapper for slides -->
  
  <div class="carousel-inner">
    <div class="item active">
      <img src="/assets/Uber.jpg" alt="uber" class="uber" >
      <div class="carousel-caption">
          <h3>Uber</h3>
      </div>
    </div>
    <div class="item">
      <img src="/assets/task.jpg" alt="task rabbit" class="task" >
      <div class="carousel-caption">
          <h3>Task Rabbit</h3>
      </div>
    </div>
    <div class="item">
      <img src="/assets/ic.jpg" alt="other independent contractors" class="ic" >
      <div class="carousel-caption">
          <h3>Other Independent Contractors</h3>
      </div>
    </div>
  </div>


 
  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div> <!-- Carousel -->



  

  <br>
  <br>
  <br>
  <br>

<%= link_to "Add Paystub", new_path  %>


  

  <br>
    
  <br>
  <br>
  <br>

<div class ="bottom">
<a href="https://www.facebook.com/zach.golman">About Us</a>
<a href="http://www.w3schools.com">Team</a>
<a href="http://www.w3schools.com">Partners</a>
<a href="http://www.w3schools.com">Contact Us</a>
<div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VHR</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
</head>
<body>

<div id="container">
    <div id="user_header">
      <% if current_user %>
        Logged in as <%= current_user.email %>.
        <%= link_to "Log Out", logout_path %>
      <% else %>
        <%= link_to "Sign Up", signup_path %> or
        <%= link_to "Log In", login_path %>
      <% end %>
    </div>
    <% flash.each do |name,msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :investment_strategy %><br />
    <%= f.text_field :investment_strategy %>
  </div>
  <div class="field">
    <%= f.label :health_insurance %><br />
    <%= f.text_field :health_insurance %>
  </div>


  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>

app/views/users/new.index.erb
<p>I'm a place holder page. I'm located in <%= users_path %> /index.html.erb </p>